services:
  server:
    container_name: application-server
    build: 
      context: ./ApplicationServer
      dockerfile: Dockerfile.prod
    env_file:
      - ./ApplicationServer/.env
    ports:
      - "5000:5000"

  liveserver:
    container_name: live-server
    build: 
      context: ./LiveServer
      dockerfile: Dockerfile.prod    
    ports:
      - "3000:3000"
    env_file:
      - ./LiveServer/.env
    depends_on:
      - server

  client:
    container_name: client
    build:
      context: ./Client
      dockerfile: Dockerfile.prod  
    ports:
      - "80:80"  
    env_file:
      - ./Client/.env
    depends_on:
      - server
      - liveserver
