export const AXINOM_CONFIG = {
	// For DRM license server configuration
	TENANT_ID: import.meta.env.AXINOM_TENANT_ID,
	WIDEVINE_LICENSE_URL: import.meta.env.AXINOM_WIDEVINE_LICENSE_URL,
	COMMUNICATION_KEY_ID: import.meta.env.AXINOM_COMMUNICATION_KEY_ID,
	COMMUNICATION_KEY: import.meta.env.AXINOM_COMMUNICATION_KEY,
	
	// For key service (content encryption)
	WIDEVINE_PROVIDER: import.meta.env.AXINOM_WIDEVINE_PROVIDER,
	WIDEVINE_SIGNING_KEY: import.meta.env.AXINOM_WIDEVINE_SIGNING_KEY,
	WIDEVINE_SIGNING_IV: import.meta.env.AXINOM_WIDEVINE_SIGNING_IV
};